version: '3.4'

services:

  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

    
  elasticsearch:  
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1

  kibana:  
    image: docker.elastic.co/kibana/kibana:7.9.1 
